const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty = v => esc(JSON.stringify(v ?? {}, null, 2));
const data = await fetch('data/architecture.json').then(r => r.json());
let view='map', technical=false, selected='payouts', production=false, workers=false, scenario=0, step=0, timer=null, stateOwner='payouts', live=null, run=null;
const node = id => data.nodes.find(n=>n.id===id);
const name = id => node(id)?.label || id;
const badge = label => `<span class="badge ${label==='Real service'?'real':label==='Contract-faithful substitute'?'contract':label==='Unknown'?'unknown':'representative'}">${esc(label)}</span>`;
const head = (title,desc,eyebrow='PAYOUTS TWIN') => `<div class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subtitle">${desc}</p></div></div>`;
const evidence = rows => (rows||[]).map(e=>`<div class="evidence-row"><strong>${esc(e.repository || e.repo)} · ${esc(e.symbol)}</strong><p class="evidence-path">${esc(e.file)}</p><small>${esc(e.confidence)} · commit ${esc(e.commit)}</small><p class="evidence-path">Local: ${esc(e.local_implementation)}</p></div>`).join('') || '<p class="caption">No narrower source reference in this view.</p>';
function table(headers, rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const positions = {client:[35,42],gateway:[260,42],payouts:[485,42],monolith:[710,42],fts:[935,42],ledger:[485,245],cfa:[35,245],xbalances:[260,245],mozart:[935,245],stork:[710,245],'webhook-sink':[935,445],dcs:[35,445],splitz:[260,445],pricing:[485,445],shield:[710,445],asv:[35,645],bankingaccounts:[260,645],cron:[485,645],workflow:[710,645],xas:[935,645],'payouts-db':[35,850],'fts-db':[260,850],'ledger-db':[485,850],'cfa-db':[710,850],'xbalances-db':[935,850],'api-db':[35,1020],redis:[260,1020],sqs:[485,1020],kafka:[710,1020]};
function graph(){
 const edges=data.edges.map((e,i)=>{const a=positions[e.from],b=positions[e.to];if(!a||!b)return '';const active=e.from===selected||e.to===selected;return `<g><path class="graph-edge ${active?'active':''}" marker-end="url(#arrow)" d="M${a[0]+95},${a[1]+70} C${a[0]+95},${a[1]+130} ${b[0]+95},${b[1]-55} ${b[0]+95},${b[1]}"/><title>${esc(name(e.from)+' → '+name(e.to)+': '+e.protocol+' · '+e.purpose)}</title>${active&&technical?`<text class="edge-label" x="${(a[0]+b[0])/2+95}" y="${(a[1]+b[1])/2+40+(i%3)*14}">${esc(e.protocol)}</text>`:''}</g>`;}).join('');
 const nodes=data.nodes.map(n=>{const [x,y]=positions[n.id];const title=production?n.production.label:n.local.label;return `<g class="graph-node ${n.id===selected?'active':''}" data-node="${n.id}" tabindex="0" role="button" aria-label="Inspect ${esc(n.label)}" transform="translate(${x},${y})"><rect width="190" height="70" rx="8"/><text class="n-label" x="12" y="27">${esc(title.length>24?title.slice(0,22)+'…':title)}</text><text class="n-detail" x="12" y="49">${esc(n.kind)}${n.workers?.length?' · '+n.workers.length+' workers':''}</text><title>${esc(title)}</title></g>`;}).join('');
 return `<svg viewBox="0 0 1160 1130" role="img" aria-label="Interactive architecture map. Select a component to inspect its connections."><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z" fill="#8ea7c8"/></marker></defs>${edges}${nodes}</svg>`;
}
function mapView(){const n=node(selected);return head('The system, one component at a time','Select a component to see what it owns, how it connects, and what changes in the local twin.')+`<div class="toolbar"><div class="segmented"><button id="local-map" class="${!production?'active':''}">Local twin</button><button id="production-map" class="${production?'active':''}">Production reference</button></div><label><input id="workers" type="checkbox" ${workers?'checked':''}> Expand worker processes</label></div><div class="legend">${data.fidelity_legend.map(x=>badge(x.label)).join('')}</div><div class="graph-layout"><div class="canvas">${graph()}</div><aside class="inspector">${badge(n.fidelity)}<h2>${esc(n.label)}</h2><p>${esc(n.summary)}</p><div class="rule"></div><h3>Production reference</h3><p>${esc(n.production.label)}: ${esc(n.production.summary)}</p><h3>Local twin</h3><p>${esc(n.local.label)}: ${esc(n.local.summary)}</p>${n.local.differences.map(x=>`<div class="callout warning">${esc(x)}</div>`).join('')}${workers?`<h3>Processes</h3><ul class="workers">${n.workers.map(w=>`<li><b>${esc(w.label)}</b><br>${esc(w.summary)}${technical?`<br><code>${esc(w.id)}</code>`:''}</li>`).join('')||'<li>No child workers.</li>'}</ul>`:''}<h3 class="subsection">Connections</h3>${data.edges.filter(e=>e.from===selected||e.to===selected).map(e=>`<div class="meta"><b>${esc(name(e.from))} → ${esc(name(e.to))}</b>${esc(e.protocol)} · ${esc(e.purpose)}${e.condition?`<br>${esc(e.condition)}`:''}</div>`).join('')}<details ${technical?'open':''}><summary>Source evidence</summary>${evidence(n.evidence)}</details></aside></div>`;}
function flowView(){const s=data.scenarios[scenario], p=s.steps[step];return head('Follow a payout','Watch the request, the transfer and the money change together.')+`<div class="toolbar"><label>Scenario <select id="scenario">${data.scenarios.map((x,i)=>`<option value="${i}" ${scenario===i?'selected':''}>${esc(x.label)}</option>`).join('')}</select></label><button id="previous" ${step===0?'disabled':''}>← Back</button><button id="play" class="primary">${timer?'Pause':'Play flow'}</button><button id="next" ${step===s.steps.length-1?'disabled':''}>Next →</button><span class="caption">${step+1} of ${s.steps.length} hops</span></div><div class="callout warning">Illustrative generated playback · ${esc(s.description)} These examples explain the source model; captured runtime evidence appears in Local runs.</div><div class="progress"><div style="width:${100*(step+1)/s.steps.length}%"></div></div><div class="flow-layout"><div class="steps">${s.steps.map((x,i)=>`<button data-step="${i}" class="${i===step?'active':''}"><span class="number">${i+1}</span><span class="step-label">${esc(x.title)}<small>${esc(name(x.from))} → ${esc(name(x.to))}</small></span></button>`).join('')}</div><article class="panel step-card"><p class="eyebrow">${esc(name(p.from))} → ${esc(name(p.to))}</p><h2 class="step-title">${esc(p.title)}</h2><p class="step-explanation">${esc(p.explanation)}</p><span class="badge">${esc(p.protocol)}</span><div class="state-pair"><div class="state-box"><span class="mini-label">BEFORE</span><pre>${pretty(p.before)}</pre></div><span aria-hidden="true">→</span><div class="state-box after"><span class="mini-label">AFTER</span><pre>${pretty(p.after)}</pre></div></div><h3>What changes</h3>${p.changes.length?table(['Owner / store','Entity','Before → after'],p.changes.map(c=>[esc(c.owner)+'<br><small>'+esc(c.store)+'</small>',esc(c.entity),`<pre>${pretty(c.before)} → ${pretty(c.after)}</pre>`])):'<p class="caption">This hop forwards or reads data without an owned-state change.</p>'}<h3 class="subsection">Synthetic payload inspector</h3><div class="payload-grid"><div><span class="mini-label">REQUEST</span><pre>${pretty(p.request)}</pre></div><div><span class="mini-label">RESPONSE</span><pre>${pretty(p.response)}</pre></div></div>${table(['Field','Meaning','Owner / origin'],p.fields.map(f=>[`<code>${esc(f.field)}</code>`,esc(f.explanation),esc(f.owner)+'<br><small>'+esc(f.origin)+'</small>']))}${p.identifiers?.length?`<details ${technical?'open':''}><summary>Identifier translations</summary><pre>${pretty(p.identifiers)}</pre></details>`:''}<details ${technical?'open':''}><summary>Source evidence and confidence</summary><p class="caption">${esc(s.confidence)}</p>${evidence(p.evidence)}</details></article></div>`;}
function statesView(){const s=data.state_machines[stateOwner];return head('Separate states, separate responsibilities','Payouts owns the merchant-facing outcome. FTS owns the bank transfer and its attempts.')+`<div class="toolbar"><div class="segmented">${Object.keys(data.state_machines).filter(k=>Array.isArray(data.state_machines[k]?.states)).map(k=>`<button data-owner="${k}" class="${stateOwner===k?'active':''}">${esc(k.toUpperCase())}</button>`).join('')}</div></div><div class="panel"><h2>${esc(s.owner)}</h2><p class="caption">Initial state: ${esc(s.initial)}</p><div class="state-section">${s.states.map(x=>`<span class="status-chip ${['processed','failed','reversed','cancelled','rejected'].includes(x.toLowerCase())?'terminal':''}">${esc(x)}</span>`).join('')}</div><h3 class="subsection">Allowed transitions and triggers</h3>${table(['From','Trigger','To',...(technical?['On entry / source']:[])],s.transitions.map(t=>[esc(Array.isArray(t.from)?t.from.join(', '):t.from),esc(t.event),`<strong>${esc(t.to)}</strong>`,...(technical?[esc((t.on_enter||[]).join('; '))+'<br><small>'+esc(t.source)+'</small>']:[])]))}</div>`;}
function ownershipView(){return head('Who owns each fact','Copied state can arrive later. Follow the owner when two views disagree.')+`<div class="grid two">${data.ownership.map(x=>`<article class="card"><p class="eyebrow">${esc(x.store)}</p><h2>${esc(x.owner)}</h2><ul>${x.owns.map(v=>`<li>${esc(v)}</li>`).join('')}</ul><p>${esc(x.explanation)}</p><div class="rule"></div><h3>Copied / eventually consistent</h3><p>${esc(x.copies.length?x.copies.join(' · '):'No copied state listed in this model.')}</p></article>`).join('')}</div>`;}
function syntheticView(){return head('Synthetic by construction','Generated identities and relationships follow source constraints. Representative choices stay labelled.')+`<div class="callout">Generator: ENV2_COMPOSE/seeds/generator/generate.py · The generated provenance manifest records field constraints, source commits, generation rules and mappings.</div><div class="grid two">${data.synthetic.map(x=>`<article class="card"><h2>${esc(x.label)}</h2>${badge(x.classification)}<p>${esc(x.explanation)}</p>${table(['Cross-service field','Synthetic value'],Object.entries(x.mapping||{}).map(([k,v])=>[`<code>${esc(k)}</code>`,esc(v)]))}<details ${technical?'open':''}><summary>Generation and evidence</summary><p class="evidence-path">${esc(x.generation)}</p>${evidence(x.evidence)}</details></article>`).join('')}</div>`;}
function evidenceView(){return head('Evidence and fidelity','Source-confirmed contracts have a limited scope. A source reference alone does not prove a live route.')+`<div class="grid two">${data.fidelity_legend.map(x=>`<div class="card">${badge(x.label)}<p>${esc(x.meaning)}</p></div>`).join('')}</div><h2 class="subsection">Independently selectable route profiles</h2>${table(['Profile','Purpose','Activation / limits'],data.route_profiles.map(x=>[`<code>${esc(x.id)}</code>`,esc(x.label),esc(x.selection)]))}<h2 class="subsection">Source references</h2><input class="search" id="evidence-search" placeholder="Filter repository, file or symbol" aria-label="Filter evidence"><div id="evidence-list" class="panel" style="margin-top:16px">${evidence(data.evidence)}</div><h2 class="subsection">Expansion points</h2><div class="grid two">${data.expansion_points.map(x=>`<div class="card"><h3>${esc(x.label)}</h3><p>${esc(x.status)}</p></div>`).join('')}</div>`;}
function liveView(){return head('Run a local synthetic payout','Start a real request through the local gateway and inspect the resulting state assertions.')+`<div class="live-grid"><div class="panel"><h2>Local arena</h2><p class="subtitle">${live?.ready?'Core services are ready.':live?.message||'Checking local services…'}</p><div class="health-list subsection">${(live?.services||[]).map(s=>`<span class="${s.ok?'':'bad'}">${esc(s.name)} · ${esc(s.status)}</span>`).join('')}</div><button id="run-golden" class="primary" ${!live?.ready||run?.status==='running'?'disabled':''}>${run?.status==='running'?'Payout running…':'Start Shared golden payout'}</button><p class="caption subsection">Uses one generated Shared merchant. A bounded local runner checks Payouts, FTS, Ledger and the signed merchant webhook.</p><button id="saved-run">Load captured saved trace</button></div><div class="panel"><h2>Captured trace</h2><div id="run-output" class="run-output">${run?renderRun(run):'<div class="empty">A live or saved captured run will appear here. For guided illustrations, open Follow a payout.</div>'}</div></div></div>`;}
function renderRun(r){const result=r.result||r;return `<div class="callout ${r.status==='failed'||result.status==='failed'?'warning':''}">${esc(r.status||result.status||'Captured result')} · ${esc(r.message||result.message||'Synthetic runtime evidence')}</div>${(result.steps||[]).map((x,i)=>`<div class="evidence-row"><span class="number">${i+1}</span><strong>${esc(x.name)}</strong><p>${x.passed?'Verified':'Failed'}</p><pre>${pretty(Object.fromEntries(Object.entries(x).filter(([k])=>!['name','passed'].includes(k))))}</pre></div>`).join('')}<details ${technical?'open':''}><summary>Full assertion result</summary><pre>${pretty(Object.fromEntries(Object.entries(result).filter(([k])=>k!=='trace')))}</pre></details>${result.trace?.length?`<h3 class="subsection">Captured requests and state reads</h3>${result.trace.map(t=>`<details><summary>${esc(t.sequence)} · ${esc(t.kind)}</summary><pre>${pretty(t.data)}</pre></details>`).join('')}`:''}`;}
function render(){const views={map:mapView,flow:flowView,states:statesView,ownership:ownershipView,synthetic:syntheticView,evidence:evidenceView,live:liveView};$('#view').innerHTML=views[view]();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));bind();}
function stop(){if(timer){clearInterval(timer);timer=null;}}
function bind(){
 document.querySelectorAll('[data-node]').forEach(el=>{const go=()=>{selected=el.dataset.node;render()};el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}}});
 if($('#local-map')){$('#local-map').onclick=()=>{production=false;render()};$('#production-map').onclick=()=>{production=true;render()};$('#workers').onchange=e=>{workers=e.target.checked;render()};}
 if($('#scenario')){$('#scenario').onchange=e=>{stop();scenario=Number(e.target.value);step=0;render()};$('#previous').onclick=()=>{stop();step--;render()};$('#next').onclick=()=>{stop();step++;render()};$('#play').onclick=()=>{if(timer){stop()}else{if(step===data.scenarios[scenario].steps.length-1)step=0;timer=setInterval(()=>{step++;if(step>=data.scenarios[scenario].steps.length-1)stop();render()},2500)}render()};document.querySelectorAll('[data-step]').forEach(el=>el.onclick=()=>{stop();step=Number(el.dataset.step);render()});}
 document.querySelectorAll('[data-owner]').forEach(el=>el.onclick=()=>{stateOwner=el.dataset.owner;render()});
 if($('#evidence-search'))$('#evidence-search').oninput=e=>{$('#evidence-list').innerHTML=evidence(data.evidence.filter(x=>JSON.stringify(x).toLowerCase().includes(e.target.value.toLowerCase())))};
 if($('#run-golden')){$('#run-golden').onclick=startRun;$('#saved-run').onclick=async()=>{try{run=await fetch('data/saved-run.json').then(r=>{if(!r.ok)throw Error('No captured trace has been saved yet.');return r.json()});render()}catch(e){toast(e.message)}};}
}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',5000);}
async function health(){const previous=JSON.stringify(live);try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw Error();live=await r.json();}catch{live={ready:false,message:'Saved mode. Start the local Python server for live controls.'}}$('#health').textContent=live.ready?'Local arena ready':'Saved exploration available';$('#health').classList.toggle('ready',!!live.ready);if(view==='live'&&JSON.stringify(live)!==previous)render();}
async function startRun(){try{const r=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json','X-Twin-Action':'golden'},body:'{}'});const x=await r.json();if(!r.ok)throw Error(x.message||'Run could not start');run=x;render();await pollRun();}catch(e){toast(e.message)}}
async function pollRun(){while(run?.status==='running'){await new Promise(r=>setTimeout(r,1500));try{const r=await fetch('/api/run',{cache:'no-store'});run=await r.json();if(view==='live')render();}catch{run={status:'failed',message:'Lost connection to the local runner.'};if(view==='live')render()}}}
$('nav').onclick=e=>{const b=e.target.closest('[data-view]');if(b){stop();view=b.dataset.view;render()}};$('#technical').onchange=e=>{technical=e.target.checked;render()};render();health();setInterval(health,30000);
