#!/usr/bin/env python3
"""Render reports/implementation/M7_FIDELITY_MATRIX.md from the canonical snapshot stats, the functional graph and
the executed journeys, so every number in the matrix is the machine-computed one."""
import json
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "reports/implementation/M7_FIDELITY_MATRIX.md"

COMPONENTS = [
    # (component, class, twin_ref, basis)
    ("payouts-api + 25 workers + 2 kafka consumers", "ACTUAL_SOURCE_RUNNING", "rzp-arena/payouts (pinned 4bf3dbf)", "M6 build provenance; journeys"),
    ("fts-web + 27 FTS workers", "ACTUAL_SOURCE_RUNNING", "rzp-arena/fts", "M6"),
    ("ledger-api + workers", "ACTUAL_SOURCE_RUNNING", "rzp-arena/ledger", "M6"),
    ("cfa-server + workers", "ACTUAL_SOURCE_RUNNING", "rzp-arena/cfa", "M6"),
    ("xbalances-server + worker", "ACTUAL_SOURCE_RUNNING", "rzp-arena/xbalances", "M6"),
    ("vendor-payments selected function slice (initiate-tds task, taxpayments core, payout client, PayoutStatusChange)", "ACTUAL_SOURCE_RUNNING", "s2p-vp-source (pinned 20c4f4d, additive driver)", "S2P runtime-fidelity-overlay: 13 symbols traced per run; M7 cross-domain journeys"),
    ("vendor-experience, accounting-integrations, unselected vendor-payments processes", "SOURCE_MAPPED_NOT_RUNNING", "built (build-manifest.json), not started", "S2P runtime-topology.yaml"),
    ("API monolith ingress: identity/tenant/ownership/idempotency/audit for 25 selected routes", "CONTRACT_FAITHFUL_REPLACEMENT", "sub:api-ingress", "contract/routes.json (Route.php-derived), 13 host tests, 10 journeys"),
    ("API monolith payouts-service callback group (pricing, credits, source_update sink, merchant config, FTS relay)", "CONTRACT_FAITHFUL_REPLACEMENT", "sub:monolith-stub (M6, reached via ingress pass-through)", "M6 CONTRACT.md, 18 tests"),
    ("SourceUpdater -> vendor-payments PayoutStatusChange transport", "CONTRACT_FAITHFUL_REPLACEMENT", "api-ingress relay -> vp-source /_replica/status", "api VendorPayments/Service.php:480 payload shape; PU-6"),
    ("Edge/Kong merchant edge", "CONTRACT_FAITHFUL_REPLACEMENT", "sub:kong-lite (M3/M6)", "M6"),
    ("Batch service", "CONTRACT_FAITHFUL_REPLACEMENT", "sub:batch-sim (create via ingress, approve PS-direct)", "M6 CONTRACT.md, 27 tests"),
    ("Workflows service (maker/checker)", "CONTRACT_FAITHFUL_REPLACEMENT", "sub:workflow-engine (M5 reconstruction)", "M5/M6"),
    ("Mozart bank gateway", "CONTRACT_FAITHFUL_REPLACEMENT", "sub:mozart-sim", "M6"),
    ("Dashboard sessions / OTP (Raven)", "BEHAVIORAL_STUB", "api-ingress control plane (/_ingress/session, /_ingress/otp)", "synthetic; PU-5"),
    ("DCS, Splitz, Shield, ASV, Stork, banking-accounts, XAS", "BEHAVIORAL_STUB / CONTRACT_FAITHFUL_REPLACEMENT per M6", "M6 substitutes", "M6 FIDELITY_CLASSIFICATION.csv"),
    ("Source-to-Pay standalone boundary (runtime/boundary/server.py)", "CONTRACT_FAITHFUL_REPLACEMENT (standalone acceptance only; not started in the arena)", "sub:s2p-monolith-boundary", "S2P declared-deviations D-MONOLITH-PAYOUTS"),
    ("Bank settlement, challan, tax filing, `paid`, accounting events", "GRAPH_ONLY / not represented", "—", "never fabricated (D-FILING-SCOPE)"),
]


def main():
    st = json.loads((REPO / "reports/architecture/M7_CANONICAL_SNAPSHOT_STATS.json").read_text())
    gs = json.loads((REPO / "reports/domain/GRAPH_STATS.json").read_text())
    jr = json.loads((REPO / "reports/implementation/m6-journeys.json").read_text())
    js = jr.get("journeys", [])
    res = Counter(j.get("result") for j in js)
    fam = {}
    for j in js:
        fam.setdefault(j.get("family"), Counter())[j.get("result")] += 1
    cov = st["coverage"]
    lab = st["label_histogram"]; p0 = st["p0_label_histogram"]
    total = sum(lab.values()); p0_total = sum(p0.values())
    rows = "\n".join("| %s | %s | %s | %s |" % c for c in COMPONENTS)
    hist = "\n".join("| %s | %d | %d |" % (k, lab.get(k, 0), p0.get(k, 0)) for k in ("ACTUAL_SOURCE_RUNNING", "CONTRACT_FAITHFUL_REPLACEMENT", "BEHAVIORAL_STUB", "SOURCE_MAPPED_NOT_RUNNING", "GRAPH_ONLY", "PRODUCTION_STATE_UNKNOWN"))
    fams = "\n".join("| %s | %s |" % (f, ", ".join("%s %d" % (k, v) for k, v in sorted(c.items()))) for f, c in sorted(fam.items()) if f)
    text = f"""# M7 — Fidelity matrix

Generated by `scripts/m7/fidelity_matrix.py` from `reports/architecture/M7_CANONICAL_SNAPSHOT_STATS.json`
(snapshot sha256 `{st.get('snapshot_sha256')}`), `reports/domain/GRAPH_STATS.json` and
`reports/implementation/m6-journeys.json` (run `{jr.get('run_dir')}`). Every material component carries exactly one
of the six M7 labels; the coverage figures are reported separately and there is no single "percent identical to
production" number.

## Coverage (reported separately)

| Measure | Value | Definition |
|---|---|---|
| Mapping coverage | {cov['mapping']['represented']}/{cov['mapping']['critical_components_total']} P0 components ({cov['mapping']['pct']}%) | P0 components identified by the discovery lanes that exist in the graph |
| Executable coverage | {cov['executable']['critical_components_executable']}/{cov['mapping']['critical_components_total']} ({cov['executable']['pct']}%) | P0 nodes whose fidelity is real_source_running or high_fidelity_replacement |
| Actual-source runtime coverage | {cov['actual_source_runtime']['p0']}/{p0_total} P0 nodes ({cov['actual_source_runtime']['p0_pct']}%); {cov['actual_source_runtime']['all_nodes']}/{total} of all nodes | label ACTUAL_SOURCE_RUNNING |
| Contract-faithful replacement coverage | {cov['contract_faithful_replacement']['p0']}/{p0_total} P0 nodes ({cov['contract_faithful_replacement']['p0_pct']}%); {cov['contract_faithful_replacement']['all_nodes']}/{total} of all nodes | label CONTRACT_FAITHFUL_REPLACEMENT |
| Behavioral stubs | {cov['behavioral_stub']['p0']} P0 / {cov['behavioral_stub']['all_nodes']} all | label BEHAVIORAL_STUB |
| Critical-journey coverage | {cov['critical_journey']['p0_families_with_passing_journey']}/{cov['critical_journey']['p0_families']} P0 families with a PASSing journey; {cov['critical_journey']['journeys_pass_or_expected']}/{cov['critical_journey']['journeys_executed']} journeys PASS or EXPECTED_FAILURE | executed suite |
| Graph size | {st['payouts_graph']['nodes']} nodes / {st['payouts_graph']['edges']} edges / {st['payouts_graph']['families']} families ({len(st['payouts_graph'].get('lanes') or [])} lanes) | functional graph after M7 lanes |
| Source-to-Pay namespace | {st['s2p_namespace']['nodes']} patch nodes / {st['s2p_namespace']['edges']} edges (referenced by hash), {cov['s2p_namespace']['projected_nodes']} projected into the functional graph, {cov['s2p_namespace']['mandatory_runtime_nodes']} mandatory runtime nodes | DOMAIN_REPLICAS/source_to_pay |

Detector limitations: {' '.join('(%d) %s' % (i + 1, x) for i, x in enumerate(cov['detector_limitations']))}

## Label histogram (functional graph)

| Label | All nodes | P0 nodes |
|---|---:|---:|
{hist}

## Material components

| Component | Label | Twin realisation | Basis |
|---|---|---|---|
{rows}

## Executed journeys by family (canonical run)

Totals: {', '.join('%s %d' % (k, v) for k, v in sorted(res.items()))}.

| Family | Results |
|---|---|
{fams}

## Actual source services running (compose services, canonical boot)

payouts-api, 25 payouts workers, 2 payouts Kafka consumers, fts-web + 27 FTS workers, ledger-api + 5 ledger workers
(+ ledger-scheduler one-shot), cfa-server + 2 CFA workers, xbalances-server + xbalances-worker, s2p-vp-source
(vendor-payments selected slice). Replacements remaining: api-ingress, monolith-stub, kong-lite, batch-sim,
workflow-engine (+ inert workflow-sim), mozart-sim, dcs-stub, splitz-stub, shield-stub, pricing-stub, asv-stub,
bankingaccounts-stub, stork-capture, merchant-webhook-sink, xas-sim, ledger-gate, cron-driver, s2p source driver.
"""
    OUT.write_text(text)
    print("wrote", OUT.relative_to(REPO))


if __name__ == "__main__":
    main()
