#!/bin/bash
# Arena LocalStack ready-hook: create every SQS queue / SNS topic the core services name in their generated configs.
set -e
export AWS_DEFAULT_REGION=ap-south-1
awslocal sqs create-queue --queue-name account_create >/dev/null && echo "queue account_create"
awslocal sqs create-queue --queue-name api-payout-service-dual-write-direct-push-live >/dev/null && echo "queue api-payout-service-dual-write-direct-push-live"
awslocal sqs create-queue --queue-name balance_update >/dev/null && echo "queue balance_update"
awslocal sqs create-queue --queue-name balance_update_pg >/dev/null && echo "queue balance_update_pg"
awslocal sqs create-queue --queue-name batch_submitted_merchants >/dev/null && echo "queue batch_submitted_merchants"
awslocal sqs create-queue --queue-name bulk_payouts >/dev/null && echo "queue bulk_payouts"
awslocal sqs create-queue --queue-name contact-dual-write-queue >/dev/null && echo "queue contact-dual-write-queue"
awslocal sqs create-queue --queue-name contact-lazy-load >/dev/null && echo "queue contact-lazy-load"
awslocal sqs create-queue --queue-name data-consistency-checker >/dev/null && echo "queue data-consistency-checker"
awslocal sqs create-queue --queue-name data-consistency-event >/dev/null && echo "queue data-consistency-event"
awslocal sqs create-queue --queue-name fmp-check >/dev/null && echo "queue fmp-check"
awslocal sqs create-queue --queue-name fmp-initiate >/dev/null && echo "queue fmp-initiate"
awslocal sqs create-queue --queue-name fts-async-hv-processing >/dev/null && echo "queue fts-async-hv-processing"
awslocal sqs create-queue --queue-name fts-async-processing >/dev/null && echo "queue fts-async-processing"
awslocal sqs create-queue --queue-name fund-account-dual-write-queue >/dev/null && echo "queue fund-account-dual-write-queue"
awslocal sqs create-queue --queue-name fund-account-lazy-load >/dev/null && echo "queue fund-account-lazy-load"
awslocal sqs create-queue --queue-name generic-processing >/dev/null && echo "queue generic-processing"
awslocal sqs create-queue --queue-name journal_create >/dev/null && echo "queue journal_create"
awslocal sqs create-queue --queue-name ledger_entry_details_create >/dev/null && echo "queue ledger_entry_details_create"
awslocal sqs create-queue --queue-name ledger_entry_details_create_pg >/dev/null && echo "queue ledger_entry_details_create_pg"
awslocal sqs create-queue --queue-name on_hold_payout >/dev/null && echo "queue on_hold_payout"
awslocal sqs create-queue --queue-name partner_bank_hold_payouts >/dev/null && echo "queue partner_bank_hold_payouts"
awslocal sqs create-queue --queue-name payout_create_failure_handling >/dev/null && echo "queue payout_create_failure_handling"
awslocal sqs create-queue --queue-name payout_update_failure_handling >/dev/null && echo "queue payout_update_failure_handling"
awslocal sqs create-queue --queue-name payout_usage_event_processing >/dev/null && echo "queue payout_usage_event_processing"
awslocal sqs create-queue --queue-name pocworker >/dev/null && echo "queue pocworker"
awslocal sqs create-queue --queue-name queued_payout >/dev/null && echo "queue queued_payout"
awslocal sqs create-queue --queue-name schedule_payout >/dev/null && echo "queue schedule_payout"
awslocal sqs create-queue --queue-name stage-x-balances-balance-refresh-live >/dev/null && echo "queue stage-x-balances-balance-refresh-live"
awslocal sqs create-queue --queue-name stage-x-balances-payouts-event >/dev/null && echo "queue stage-x-balances-payouts-event"
awslocal sqs create-queue --queue-name transaction_create >/dev/null && echo "queue transaction_create"
awslocal sqs create-queue --queue-name webhook_event >/dev/null && echo "queue webhook_event"
awslocal sns create-topic --name payout-updates-test-dev >/dev/null && echo "topic payout-updates-test-dev"
awslocal sns create-topic --name journal-created >/dev/null && echo "topic journal-created"
awslocal sqs create-queue --queue-name payout-source-updater >/dev/null && echo "queue payout-source-updater"
awslocal sqs create-queue --queue-name payouts-async-dual-write >/dev/null && echo "queue payouts-async-dual-write"
