#!/usr/bin/env python3
"""M6 lane I4 -- business-journey runner.

    python3 RED_LOOP/m6/journeys/run.py [--only id,id] [--family f] [--list]

Runs the registered journey drivers against the LIVE arena on fresh synthetic
merchants and writes

    reports/implementation/m6-journeys.json          machine-readable results
    reports/implementation/m6-journey-coverage.md    family x variant matrix
    RED_LOOP/runs/m6-journeys-<ts>/                  evidence bundle (git-ignored)

Options
    --only     comma-separated journey ids or bare variants ("shared-payouts/success",
               "journey:webhooks/failure", or a substring match)
    --family   comma-separated family slugs (shared-payouts, direct-payouts, ...)
    --list     print the registry and exit
    --campaign fixed campaign prefix (reuses the same deterministic fresh merchants
               across iterations instead of minting a new set)
    --run-dir  reuse an existing run directory
"""
import argparse
import json
import os
import sys
from collections import OrderedDict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import framework as F  # noqa: E402


VARIANT_ORDER = ["success", "failure", "pending", "retry", "duplicate", "idempotency",
                 "cancel_or_reverse", "concurrency", "maker_checker", "n_of_m", "accounting",
                 "webhook", "restart", "async_state", "tenant_isolation", "cfa_api"]


def select(specs, only, families):
    out = specs
    if families:
        want = {f.strip().replace("family:", "") for f in families.split(",") if f.strip()}
        out = [s for s in out if s["family_slug"] in want]
    if only:
        keys = [k.strip() for k in only.split(",") if k.strip()]
        picked = []
        for s in out:
            for k in keys:
                if k == s["id"] or k == s["id"].replace("journey:", "") or k in s["id"]:
                    picked.append(s)
                    break
        out = picked
    return out


def coverage_md(doc, path):
    rows = doc["journeys"]
    fams = OrderedDict()
    for r in rows:
        fams.setdefault(r["family"], {})[r["variant"]] = r
    variants = [v for v in VARIANT_ORDER if any(v in f for f in fams.values())]
    extra = sorted({v for f in fams.values() for v in f} - set(variants))
    variants += extra
    sym = {F.PASS: "PASS", F.FAIL: "**FAIL**", F.EXPECTED_FAILURE: "EF", F.BLOCKED: "BLOCKED"}

    L = []
    L.append("# M6 business-journey coverage (lane I4)")
    L.append("")
    L.append("Generated by `python3 RED_LOOP/m6/journeys/run.py`. Every cell is a driver that")
    L.append("actually executed against the live arena (compose project `%s`) on a fresh"
             % (doc.get("fingerprint") or {}).get("compose_project", "env2_compose"))
    L.append("synthetic merchant. Nothing in this table is asserted by writing DB state directly.")
    L.append("")
    L.append("| field | value |")
    L.append("|---|---|")
    L.append("| run_dir | `%s` |" % doc["run_dir"])
    L.append("| git_head | `%s` |" % doc["git_head"])
    L.append("| arena boot_id | `%s` |" % (doc.get("fingerprint") or {}).get("boot_id"))
    L.append("| arena route_profile | `%s` |" % (doc.get("fingerprint") or {}).get("route_profile"))
    L.append("| arena config_digest | `%s` |" % (doc.get("fingerprint") or {}).get("config_digest"))
    L.append("| generated_at | %s |" % doc["generated_at"])
    L.append("")
    tot = doc["summary"]
    L.append("**%d journeys — %d PASS, %d FAIL, %d EXPECTED_FAILURE, %d BLOCKED**"
             % (tot["total"], tot["pass"], tot["fail"], tot["expected_failure"], tot["blocked"]))
    L.append("")
    L.append("## Family x variant matrix")
    L.append("")
    L.append("| family | " + " | ".join(variants) + " |")
    L.append("|" + "---|" * (len(variants) + 1))
    for fam, cells in fams.items():
        line = ["`%s`" % fam]
        for v in variants:
            r = cells.get(v)
            line.append(sym.get(r["result"], r["result"]) if r else "–")
        L.append("| " + " | ".join(line) + " |")
    L.append("")
    L.append("Legend: PASS = every assertion held · **FAIL** = a real observed defect ")
    L.append("(reported, not patched) · EF = EXPECTED_FAILURE, the twin reproduced a documented ")
    L.append("source/expected-failures.yaml behaviour · BLOCKED = arena dependency missing · – = ")
    L.append("variant not applicable to that family.")
    L.append("")
    L.append("## P0 acceptance gate (success + failure + idempotency + async_state per P0 family)")
    L.append("")
    L.append("| P0 family | " + " | ".join(F.REQUIRED_P0_VARIANTS) + " | gate |")
    L.append("|" + "---|" * (len(F.REQUIRED_P0_VARIANTS) + 2))
    for slug in F.P0_FAMILIES:
        fam = F.FAMILIES[slug]
        cells = fams.get(fam, {})
        line = ["`%s`" % fam]
        ok = True
        for v in F.REQUIRED_P0_VARIANTS:
            r = cells.get(v)
            line.append(sym.get(r["result"], "–") if r else "–")
            if not r or r["result"] not in (F.PASS, F.EXPECTED_FAILURE):
                ok = False
        line.append("MET" if ok else ("NOT RUN in this selection" if not cells else "NOT MET"))
        L.append("| " + " | ".join(line) + " |")
    L.append("")
    L.append("## Journeys")
    L.append("")
    L.append("| id | priority | result | fidelity | merchant | s | notes |")
    L.append("|---|---|---|---|---|---|---|")
    for r in rows:
        notes = r.get("missing_dependency") or r.get("expected_failure_ref") or r.get("notes") or ""
        if r.get("failed_checks"):
            notes = ("failed: " + ", ".join(r["failed_checks"][:3]) + " | " + notes)[:300]
        L.append("| `%s` | %s | %s | %s | `%s` | %s | %s |" % (
            r["id"], r["priority"], sym.get(r["result"], r["result"]), r["fidelity"],
            r.get("merchant_id") or "-", r["duration_s"], str(notes).replace("|", "/")[:220]))
    L.append("")
    if doc.get("provisioner_findings", {}).get("ledger_account_id_collisions"):
        L.append("## Provisioning findings hit during this run")
        L.append("")
        L.append("| merchant minted | ledger acc prefix | accounts it owns | prefix already owned by |")
        L.append("|---|---|---|---|")
        for c in doc["provisioner_findings"]["ledger_account_id_collisions"]:
            L.append("| `%s` | `%s` | %s | %s |" % (c["merchant_id"], c["ledger_acc_prefix"],
                                                    c["accounts_owned"],
                                                    ", ".join("`%s`" % o for o in c["prefix_owned_by"])))
        L.append("")
        L.append("REGRESSION. `RED_LOOP/red_loop/provisioner.py` `_ledger_acc_prefix` is supposed to be")
        L.append("injective over the Shared merchant-number range (M6 lane I5 fix, proved by")
        L.append("`tests/test_ledger_ids.py` over 10,000 campaigns), so a row here means two fresh")
        L.append("merchants shared a ledger account-id namespace again. The failure mode is silent:")
        L.append("`provision_funded_merchant` inserts `accounts` / `account_details` with")
        L.append("`ON CONFLICT (id) DO NOTHING` and records the step as ok regardless, so the colliding")
        L.append("merchant ends up with ZERO ledger accounts while its descriptor still reports")
        L.append("`verified: true`. This lane detects it and re-mints on a different deterministic id;")
        L.append("the provisioner itself is another lane's file and was not modified.")
        L.append("")
    L.append("## Blocked journeys and their exact missing dependency")
    L.append("")
    blocked = [r for r in rows if r["result"] == F.BLOCKED]
    if not blocked:
        L.append("_none_")
    else:
        L.append("| id | missing dependency |")
        L.append("|---|---|")
        for r in blocked:
            L.append("| `%s` | %s |" % (r["id"], str(r.get("missing_dependency", "")).replace("|", "/")))
    L.append("")
    Path(path).write_text("\n".join(L) + "\n")
    return path


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--only")
    ap.add_argument("--family")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--campaign", default=None)
    ap.add_argument("--run-dir")
    args = ap.parse_args()

    mods = F.load_drivers()
    specs = sorted(F.REGISTRY, key=lambda s: (
        list(F.FAMILIES).index(s["family_slug"]),
        s["order"] if s.get("order") is not None
        else (VARIANT_ORDER.index(s["variant"]) if s["variant"] in VARIANT_ORDER else 99)))

    if args.list:
        for s in specs:
            print("%-8s %-46s profile=%-8s %s" % (s["priority"], s["id"], s["profile"], s["title"]))
        print("\n%d journeys in %d driver modules: %s" % (len(specs), len(mods), ", ".join(mods)))
        return 0

    chosen = select(specs, args.only, args.family)
    if not chosen:
        print("no journeys selected")
        return 2

    # The reboot owner delegates three worker containers to journey:shared-payouts/restart
    # (payouts-worker-fts-async-processing, payouts-worker-webhook-event,
    #  fts-worker-fire-transfer-status-webhook). That journey restarts ONLY those three and
    # nothing else; set M6_ALLOW_RESTART=0 in the environment to keep it BLOCKED instead.
    os.environ.setdefault("M6_ALLOW_RESTART", "1")

    stamp = F.ts()
    run_dir = Path(args.run_dir) if args.run_dir else F.RUNS / ("m6-journeys-" + stamp)
    run_dir.mkdir(parents=True, exist_ok=True)
    campaign = args.campaign or ("m6i4-" + stamp[2:13].lower())

    pool = F.MerchantPool(run_dir, campaign)
    runner = F.Runner(run_dir, pool)
    print("run_dir  = %s" % run_dir)
    print("campaign = %s   (fresh deterministic ARENA-prefixed merchants)" % campaign)
    print("journeys = %d\n" % len(chosen))

    arena_ok = F.Arena({}).ps_healthy()
    if not arena_ok:
        print("WARNING: payouts-api is not reporting healthy; journeys will record what they observe")

    for spec in chosen:
        runner.run_one(spec)

    rows = runner.results
    summary = {"total": len(rows),
               "pass": sum(1 for r in rows if r["result"] == F.PASS),
               "fail": sum(1 for r in rows if r["result"] == F.FAIL),
               "expected_failure": sum(1 for r in rows if r["result"] == F.EXPECTED_FAILURE),
               "blocked": sum(1 for r in rows if r["result"] == F.BLOCKED)}
    doc = {"schema_version": 1, "lane": "I4 business-journeys", "milestone": "M6",
           "generated_at": F.now(), "run_dir": str(run_dir.relative_to(F.REPO)),
           "git_head": F.git_head(), "fingerprint": F.fingerprint(),
           "campaign_prefix": campaign,
           "merchants": pool.setup_log,
           "provisioner_findings": {"ledger_account_id_collisions": pool.collisions},
           "summary": summary,
           "journeys": [{k: v for k, v in r.items() if k != "title"} for r in rows]}
    F.save(F.IMPL / "m6-journeys.json", doc)
    coverage_md(doc, F.IMPL / "m6-journey-coverage.md")
    F.save(run_dir / "summary.json", doc)

    print("\n" + json.dumps(summary))
    print("reports/implementation/m6-journeys.json")
    print("reports/implementation/m6-journey-coverage.md")
    return 0 if summary["fail"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
