-- ledger.postgres.sql
-- ledger core schema — CONFIRMED PostgreSQL (not MySQL; see report body for the full engine-identity
-- evidence chain). Derived MECHANICALLY from ledger/internal/database/pg_migrations/*.go (goose,
-- source of truth; internal/database/migrations/ is a CI-generated byte-identical copy per
-- .github/workflows/review_ci.yml:34-35). NO DATA ROWS.
--
-- MySQL exists in this repo ONLY for: (a) a disabled-by-default (isEnabled=false) "makeshift" shadow
-- subsystem (internal/makeshift/*, its own MySQL-flavored migrations, tables transactions/balance/
-- credit_transaction — NOT reproduced here, out of scope for the ledger's real schema), and
-- (b) external apiDb/apiTiDb connections to the API monolith (not ledger-owned).
--
-- KNOWN INVARIANT GAP (not a schema drift, but load-bearing for the twin): the journal dedup key
-- (transactor_id, transactor_event) has NO unique index/constraint anywhere in pg_migrations/ —
-- exhaustive grep for UNIQUE across all 51 files returns only account_details, ledger_config,
-- onboarding_events, none on journal. Dedup is pure application-layer check-then-insert
-- (internal/journal/validation.go:353-369 SELECT, then repo.go INSERT) — a real race window. A twin
-- that wants to be MORE correct than production could add the constraint below (commented out); to
-- reproduce production behaviour faithfully, do NOT add it.

CREATE TABLE IF NOT EXISTS accounts ( -- 20201001011117_create_accounts.go:15-25
  id               CHAR(14)       PRIMARY KEY,
  merchant_id      CHAR(14)       NOT NULL,
  status           VARCHAR(20)    NOT NULL,             -- app enum only (ACTIVATED/IN_REVIEW/ARCHIVED/SUSPENDED), no DB CHECK
  balance          NUMERIC(26,6)  DEFAULT 0,             -- widened from NUMERIC(20,6) by 20211020131618; default added by 20210517133655
  min_balance      NUMERIC(26,6),
  negative_balance NUMERIC(26,6),
  created_at       INTEGER        NOT NULL,
  updated_at       INTEGER        NOT NULL,
  deleted_at       INTEGER
);
CREATE INDEX ON accounts(merchant_id); -- 20201001011117_create_accounts.go:30

CREATE TABLE IF NOT EXISTS journal ( -- 20201001011143_create_journal.go:15-29 + renames/widenings below
  id                     CHAR(14)      NOT NULL,
  merchant_id            CHAR(14)      NOT NULL,
  amount                 NUMERIC(26,6) NOT NULL,        -- widened from NUMERIC(20,6) by 20211020131618:32
  base_amount            NUMERIC(26,6) NOT NULL,        -- widened by 20211020131618:38
  currency               CHAR(3)       NOT NULL,
  transactor_id          VARCHAR(50)   NOT NULL,        -- was CHAR(14), widened by 20210416152026_alter_transactor_id_column.go:14
  transactor_event       VARCHAR(60)   NOT NULL,        -- renamed from transactor_type by 20210925113658_rename_transactor_type_to_transactor_event_in_journal_go.go:15
  transaction_date       INTEGER       NOT NULL,
  created_at             INTEGER       NOT NULL,
  updated_at             INTEGER       NOT NULL,
  created_at_microsecond BIGINT        DEFAULT (extract(epoch FROM now())*1000000)::BIGINT,
  updated_at_microsecond BIGINT        DEFAULT (extract(epoch FROM now())*1000000)::BIGINT,
  tenant                 VARCHAR(50)   DEFAULT NULL,    -- added by 20210826041041; nullable at DB level though app requires it (validation.go — soft drift, see report)
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE(created_at);
-- default partition `journal_default` per 20201001011143_create_journal.go:54
CREATE INDEX ON journal(merchant_id);    -- :34
CREATE INDEX ON journal(transactor_id);  -- :39 (plain, NOT unique)
CREATE INDEX ON journal(id);             -- :44
CREATE INDEX ON journal(created_at);     -- :49 (partition pruning)
-- CREATE UNIQUE INDEX ON journal(transactor_id, transactor_event, tenant); -- DOES NOT EXIST IN PRODUCTION, see header — do not enable for a faithful twin

CREATE TABLE IF NOT EXISTS ledger_entries ( -- 20201001011149_create_ledger_entries.go:15-29 + additions below
  id                     CHAR(14)      NOT NULL,
  merchant_id            CHAR(14)      NOT NULL,
  journal_id             CHAR(14)      NOT NULL,
  account_id             CHAR(14)      NOT NULL,
  amount                 NUMERIC(26,6) NOT NULL,        -- widened by 20211020131618:44
  base_amount            NUMERIC(26,6) NOT NULL,        -- widened by 20211020131618:50
  type                   VARCHAR(20)   NOT NULL,        -- app enum only (credit/debit), no DB CHECK/ENUM
  currency               CHAR(3)       NOT NULL,
  created_at             INTEGER       NOT NULL,
  updated_at             INTEGER       NOT NULL,
  created_at_microsecond BIGINT        DEFAULT (extract(epoch FROM now())*1000000)::BIGINT,
  updated_at_microsecond BIGINT        DEFAULT (extract(epoch FROM now())*1000000)::BIGINT,
  balance                NUMERIC(26,6) DEFAULT NULL,    -- added 20210628101139; per-entry async snapshot, NOT a running SUM
  balance_updated        BOOLEAN       DEFAULT FALSE,   -- added 20211020100711
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE(created_at);
-- default partition `ledger_entries_default` per 20201001011149_create_ledger_entries.go:49
CREATE INDEX ON ledger_entries(journal_id);              -- :34
CREATE INDEX ON ledger_entries(created_at_microsecond);  -- :39
CREATE INDEX account_id_created_at_microsecond_idx ON ledger_entries (account_id, created_at_microsecond); -- :44, backs the balance-catchup backlog query

CREATE TABLE IF NOT EXISTS account_details ( -- 20201022184734_create_account_details.go:15-30 + additions
  id                 CHAR(14)      PRIMARY KEY,
  account_id         CHAR(14)      NOT NULL UNIQUE,
  account_name       VARCHAR(255)  NOT NULL,
  merchant_id        CHAR(14)      NOT NULL,
  parent_account_id  CHAR(14),
  currency           CHAR(3)       NOT NULL,
  account_category   VARCHAR(20)   NOT NULL,  -- app enum: Asset/Liability/Revenue/Equity/Gain/Loss/Expense, no DB CHECK
  business_category  VARCHAR(20)   NOT NULL,  -- app enum: Real/Nominal/Personal, no DB CHECK
  entities           jsonb,
  description        text,
  created_at         INTEGER       NOT NULL,
  updated_at         INTEGER       NOT NULL,
  deleted_at         INTEGER,
  tenant             VARCHAR(50),             -- added 20210826041040
  use_split_accounts SMALLINT      DEFAULT 0  -- added 20221211115222
  -- onboarding_events VARCHAR(255)[] was added then DROPPED by 20230920171333 — do not include
);
CREATE INDEX ON account_details USING GIN (entities);                                  -- :32
CREATE UNIQUE INDEX ON account_details(account_name) WHERE deleted_at IS NULL;         -- :37
CREATE INDEX ON account_details(merchant_id);                                          -- :42
CREATE INDEX idx_account_details_tenant_currency_parent_account ON account_details (tenant, currency) WHERE parent_account_id IS NULL AND deleted_at IS NULL; -- 20260619120000 (was applied out-of-band on prod first via CREATE INDEX CONCURRENTLY, DBRE ticket ISS-2747887; this migration is an idempotent IF NOT EXISTS no-op there)

-- Real Postgres-native ENUM types (the ONLY tables in ledger that use them — contrast with
-- journal/ledger_entries/accounts/account_details above, which are plain VARCHAR + app validation):
CREATE TYPE state_change_logs_refer_tables AS ENUM ('accounts');                                         -- 20221128052500_alter_state_change_logs_table.go
CREATE TYPE state_change_logs_events       AS ENUM ('activated','archived','suspended');
CREATE TYPE state_change_logs_status       AS ENUM ('ACTIVATED','IN_REVIEW','ARCHIVED','SUSPENDED');
CREATE TYPE state_change_logs_mode         AS ENUM ('SYSTEM','MANUAL');
CREATE TYPE split_accounts_entry_type      AS ENUM ('credit','debit');                                    -- 20221211114222_create_split_accounts.go:14-20

CREATE TABLE IF NOT EXISTS idempotency ( -- 20210527121244_create_idempotency.go — separate HTTP-level idempotency table, unrelated to journal transactor dedup
  id              CHAR(14) PRIMARY KEY,
  idempotency_key VARCHAR(255) NOT NULL,
  created_at      INTEGER NOT NULL
);
CREATE INDEX idempotency_key_created_at_idx ON idempotency(idempotency_key, created_at); -- :31

-- ledger_config, onboarding_events, split_accounts, outbox_jobs_*, journal_rejected_events also exist
-- (internal/database/pg_migrations/) but were not required for the twin's own seeds/s4/ledger.sql and
-- are omitted here; see ledger_config's two partial-UNIQUE indexes ((tenant,transactor_event_name)
-- and (tenant,rule), both WHERE deleted_at IS NULL) if config-driven behaviour is ever seeded.
