#!/usr/bin/env python3
"""Explicit-manifest Daytona runner. Dry run imports no SDK and calls no API."""
from __future__ import annotations
import argparse
import hashlib
import importlib.metadata
import inspect
import json
import math
import os
from pathlib import Path, PurePosixPath
import shlex
import signal
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid

ROOT = Path(__file__).resolve().parents[2]
# Schema 2 checks, produced by ENV2_COMPOSE/scripts/local-acceptance.py. Schema 1
# was hand-authored and conflated route fidelity with product-route health; it is
# rejected outright rather than mapped forward.
ACCEPTANCE_SCHEMA_VERSION = 2
CHECKS = ('fresh_build', 'empty_volume_boot', 'runtime_endpoint_audit',
          'secret_scan', 'egress_same_window', 'verifier_suite',
          'logical_replay', 'route_fidelity', 'resource_profile',
          'explorer_saved_and_live', 'staleness', 'declared_deviations_present',
          'fixed_twin_defects_recorded', 'no_unexplained_results')
REMOTE = '/tmp/payouts-twin'


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def digest(path):
    h = hashlib.sha256()
    with Path(path).open('rb') as f:
        for block in iter(lambda: f.read(1024 * 1024), b''):
            h.update(block)
    return h.hexdigest()


def read(path):
    return json.loads(Path(path).read_text())


def write(path, data):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix('.tmp')
    temporary.write_text(json.dumps(data, indent=2) + '\n')
    temporary.chmod(0o600)
    temporary.replace(path)


def utc():
    return time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())


def rooted(path):
    p = (ROOT / path).resolve()
    require(p.is_relative_to(ROOT), 'Evidence must be inside this checkout')
    return p


def check_evidence(entries):
    require(bool(entries), 'No hashed evidence supplied')
    for entry in entries:
        p = rooted(entry['path'])
        require(p.is_file() and digest(p) == entry['sha256'],
                'Evidence absent or changed: ' + entry['path'])


def acceptance(path):
    data = read(path)
    require(data.get('schema_version') == ACCEPTANCE_SCHEMA_VERSION,
            'Local acceptance must be schema_version ' + str(ACCEPTANCE_SCHEMA_VERSION) +
            ' generated by ENV2_COMPOSE/scripts/local-acceptance.py; found ' +
            repr(data.get('schema_version')))
    require(data.get('status') == 'passed', 'Local acceptance has not passed')
    for key in CHECKS:
        require(data.get('checks', {}).get(key) is True, 'Local acceptance missing: ' + key)
    # route_fidelity passing while a product route is red is expected and declared;
    # an unexplained result is not. Entries carrying a fixed_defect_ref are
    # attributed to a corrected twin defect and are informational, matching the
    # producer's own no_unexplained_results rule.
    require(not [u for u in data.get('unexplained_results') or []
                 if not u.get('fixed_defect_ref')],
            'Local acceptance lists unexplained results')
    check_evidence(data.get('evidence_files', []))
    return data


def resource_selection(profile):
    """Round measured full-arena peaks upward; no claim this is capacity-tested."""
    require(profile.get('schema_version') == 1, 'Unsupported resource profile')
    phases = profile.get('phases', {})
    for phase in ('idle', 'successful_payout', 'full_verifier'):
        p = phases.get(phase, {})
        require(p.get('observed') is True and p.get('sample_count', 0) >= 2,
                'Missing measured resource phase: ' + phase)
        require(all(isinstance(p.get(k), (int, float)) and p[k] > 0
                    for k in ('peak_cpu_cores', 'peak_memory_gib', 'disk_gib')),
                'Invalid resource measurements: ' + phase)
    return {
        'cpu': max(2, math.ceil(max(p['peak_cpu_cores'] for p in phases.values()) * 1.25)),
        'memory_gib': max(4, math.ceil(max(p['peak_memory_gib'] for p in phases.values()) * 1.25 + 2)),
        'disk_gib': math.ceil(max(p['disk_gib'] for p in phases.values()) * 1.25 + 10),
    }


def validate_plan(path):
    plan = read(path)
    acceptance(rooted(plan['local_acceptance']))
    check_evidence(plan.get('evidence_files', []))
    require(bool(plan.get('company_policy_reference')), 'Company authorization reference missing')
    require(plan.get('transfer_approved') is True, 'Exact transfer manifest not approved')
    profile_path = rooted(plan['resource_profile'])
    require(any(e['path'] == plan['resource_profile'] for e in plan['evidence_files']),
            'Resource profile must be hash-bound in evidence_files')
    selected = resource_selection(read(profile_path))
    require(plan.get('resources') == selected, 'Use measured minimum resource selection: ' + json.dumps(selected))
    require(5 <= plan.get('ttl_minutes', 0) <= 120, 'Hard TTL must be 5–120 minutes')
    require(plan.get('snapshot', {}).get('docker_compose_validated') is True,
            'Approved snapshot Docker/Compose capability has not been validated')
    require(bool(plan['snapshot'].get('name')), 'Approved snapshot name missing')
    require(plan.get('setup_domains') == [], 'This package supports offline setup only; setup_domains must be []')
    require(plan.get('secret_scan_passed') is True, 'Bundle/image secret scan missing')
    require(plan.get('offline_compose_rehearsal_passed') is True,
            'Offline Compose rehearsal with exported images must pass locally first')
    entries = plan.get('files', [])
    require(bool(entries), 'Explicit upload file manifest is empty')
    destinations = set()
    for entry in entries:
        dst = PurePosixPath(entry['destination'])
        require(not dst.is_absolute() and '..' not in dst.parts and str(dst) != '.', 'Unsafe upload destination')
        require(str(dst) not in destinations, 'Duplicate upload destination')
        destinations.add(str(dst))
        require('.git' not in dst.parts and 'generated' not in dst.parts,
                'Do not upload git history or rendered configuration')
        if 'secrets' in dst.parts:
            require(dst.name in ('gen-secrets.sh', 'destroy.sh'), 'Synthetic runtime secrets must be generated remotely')
        source = rooted(entry['source'])
        require(not (ROOT / entry['source']).is_symlink(), 'Do not upload symlinks')
        require(source.is_file() and digest(source) == entry['sha256'], 'Upload content changed: ' + entry['source'])
    for path in ('images.tar', 'ENV2_COMPOSE/docker-compose.yml', 'ENV2_COMPOSE/.env.arena',
                 'DAYTONA/scripts/remote-run.sh'):
        require(path in destinations, 'Upload manifest missing: ' + path)
    return plan


def dry_run(action, plan_path):
    result = {
        'mode': 'dry-run', 'action': action, 'remote_api_calls': 0,
        'sandbox_created': False, 'resource_minutes_consumed': 0,
        'approval_required': 'DAYTONA_APPROVED=1 and passed local acceptance',
        'resource_estimate': None,
        'provisional_planning_envelope': {'cpu': 4, 'memory_gib': 16, 'disk_gib': 64,
                                          'basis': 'unmeasured placeholder; never used for allocation'},
        'sequence': ['verify acceptance/evidence/approved manifest', 'select resources from local measured peaks',
                     'create approved empty Docker snapshot with outbound block + hard TTL',
                     'upload only approved hash-bound files', 'load prebuilt images offline',
                     'smoke with preflight/DNS/packet audit', 'full only after smoke passes',
                     'export results even on failure', 'delete in finally', 'verify API HTTP 404'],
        'blockers': [],
    }
    try:
        plan = validate_plan(plan_path)
        result['resource_estimate'] = plan['resources']
        result['resource_estimate_source'] = {'kind':'validated_execution_plan',
                                              'profile':plan['resource_profile']}
        result.pop('provisional_planning_envelope', None)
        result['ttl_minutes'] = plan['ttl_minutes']
    except (OSError, ValueError, KeyError, RuntimeError) as exc:
        result['blockers'].append(str(exc))
    if result['resource_estimate'] is None:
        # Planning is read-only and does not require permission to execute. Do
        # not follow a profile path from an unvalidated plan: only this fixed,
        # workspace-contained evidence file is eligible for the fallback.
        profile_name = 'reports/implementation/resource-profile.json'
        try:
            raw = rooted(profile_name).read_bytes()
            profile = json.loads(raw)
            result['resource_estimate'] = resource_selection(profile)
            result['resource_estimate_source'] = {
                'kind':'workspace_measured_planning_floor', 'profile':profile_name,
                'sha256':hashlib.sha256(raw).hexdigest(),
                'updated_at':profile.get('updated_at'),
                'execution_authorized':False,
                'limits':'Sampled Compose-container use plus fixed allowances; unmeasured daemon/VM, standalone capture/analyzer and staging overhead still require review.',
            }
            result.pop('provisional_planning_envelope', None)
        except (OSError, ValueError, KeyError, TypeError, OverflowError, RuntimeError) as exc:
            result['blockers'].append('Workspace resource estimate unavailable: ' + str(exc))
    try:
        result['installed_sdk_version'] = importlib.metadata.version('daytona')
    except importlib.metadata.PackageNotFoundError:
        result['blockers'].append('Daytona Python SDK is not installed; execution capability unverified')
    print(json.dumps(result, indent=2))


def load_sdk():
    try:
        from daytona import Daytona, CreateSandboxFromSnapshotParams, Sandbox
    except ImportError as exc:
        raise RuntimeError('Daytona SDK unavailable; no automatic installation or sandbox creation') from exc
    fields = getattr(CreateSandboxFromSnapshotParams, 'model_fields', {})
    require(all(k in fields for k in ('ttl_minutes', 'network_block_all', 'auto_delete_interval')),
            'Installed SDK lacks verified TTL/network/cleanup create parameters')
    for cls, method, keywords in ((Sandbox, 'update_network_settings', ['network_block_all']),
                                  (Daytona, 'delete', ['wait', 'timeout']),
                                  (Daytona, 'get', ['request_timeout'])):
        sig = inspect.signature(getattr(cls, method))
        require(all(k in sig.parameters for k in keywords), 'Installed SDK capability mismatch: ' + method)
    return Daytona, CreateSandboxFromSnapshotParams


def exists_via_api(identifier):
    """Only an authenticated 404 proves absence; auth/network/server errors fail closed."""
    base = os.environ.get('DAYTONA_API_URL', 'https://app.daytona.io/api').rstrip('/')
    require(urllib.parse.urlparse(base).scheme == 'https', 'Daytona API must use HTTPS')
    key = os.environ.get('DAYTONA_API_KEY')
    require(bool(key), 'DAYTONA_API_KEY must remain only in the local controller environment')
    request = urllib.request.Request(base + '/sandbox/' + urllib.parse.quote(identifier, safe=''),
                                     headers={'Authorization': 'Bearer ' + key})
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            require(response.status == 200, 'Unexpected API verification status')
            return True
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return False
        raise RuntimeError('Deletion verification HTTP ' + str(exc.code)) from None


class Run:
    def __init__(self, state_path, plan=None):
        Daytona, self.Params = load_sdk()
        self.client = Daytona()
        self.path = Path(state_path)
        self.state = read(self.path) if self.path.exists() else {}
        self.plan = plan

    def save(self):
        write(self.path, self.state)

    def sandbox(self):
        return self.client.get(self.state.get('sandbox_id') or self.state['sandbox_name'], request_timeout=30)

    def create(self):
        require(not self.state, 'State already exists; use a new run directory')
        self.state = {'sandbox_name': 'payouts-twin-' + uuid.uuid4().hex[:16],
                      'created_request_at': utc(), 'started_epoch': time.time(),
                      'resources_requested': self.plan['resources'], 'ttl_minutes': self.plan['ttl_minutes'],
                      'sandbox_id': None, 'cleanup_verified': False, 'test_result': 'not-run'}
        self.save()  # Name is durable even if creation times out before returning an ID.
        sb = self.client.create(self.Params(name=self.state['sandbox_name'],
            snapshot=self.plan['snapshot']['name'], public=False, network_block_all=True,
            ttl_minutes=self.plan['ttl_minutes'], auto_delete_interval=0, auto_stop_interval=0,
            volumes=[], env_vars={}, labels={'purpose': 'synthetic-payouts-twin'}), timeout=120)
        self.state.update(sandbox_id=sb.id, creation_time=utc(),
                          resources_allocated={'cpu': sb.cpu, 'memory_gib': sb.memory, 'disk_gib': sb.disk})
        self.save()
        require(self.state['resources_allocated'] == self.plan['resources'],
                'Snapshot allocation differs from measured selection; deleting without upload')
        sb.refresh_data()
        require(bool(getattr(sb, 'auto_destroy_at', None)), 'Server did not confirm hard TTL')
        require(sb.network_block_all is True, 'Server did not confirm blocked outbound network')

    def command(self, command, log, timeout=120):
        result = self.sandbox().process.exec(command, timeout=timeout)
        (self.path.parent / log).write_text(result.result or '')
        require(result.exit_code == 0, 'Remote command failed; see ' + log)

    def upload(self):
        sb = self.sandbox()
        sb.fs.create_folder(REMOTE, '700')
        made = {REMOTE}
        for entry in self.plan['files']:
            source = rooted(entry['source'])
            require(digest(source) == entry['sha256'], 'Upload changed after gate')
            remote = REMOTE + '/' + entry['destination']
            parent = str(PurePosixPath(remote).parent)
            if parent not in made:
                sb.fs.create_folder(parent, '700')
                made.add(parent)
            sb.fs.upload_file(str(source), remote, timeout=300)
            sb.fs.set_file_permissions(remote, mode='700' if os.access(source, os.X_OK) else '600')
        self.command('docker info >/dev/null && docker compose version && docker load -i ' +
                     shlex.quote(REMOTE + '/images.tar'), 'image-load.log', timeout=300)
        self.state['uploaded'] = True
        self.save()

    def test(self, profile):
        require(self.state.get('uploaded'), 'Upload/load must complete before running')
        require(profile == 'smoke' or self.state.get('smoke_result') == 'passed', 'Full requires passed smoke')
        sb = self.sandbox()
        sb.update_network_settings(network_block_all=True, request_timeout=30)
        sb.refresh_data()
        require(sb.network_block_all is True, 'Runtime outbound network block not confirmed')
        self.state['test_result'] = profile + '-running'
        self.save()
        try:
            self.command('timeout --signal=TERM --kill-after=20s 1700s bash ' + REMOTE + '/DAYTONA/scripts/remote-run.sh ' + profile,
                         profile + '.log', timeout=1800)
            self.state[profile + '_result'] = 'passed'
            self.state['test_result'] = profile + '-passed'
        except BaseException:
            self.state[profile + '_result'] = 'failed'
            self.state['test_result'] = profile + '-failed'
            raise
        finally:
            self.save()

    def export(self):
        self.command('mkdir -p ' + REMOTE + '/results && tar -czf /tmp/payouts-twin-results.tar.gz -C ' +
                     REMOTE + ' results', 'export.log', timeout=60)
        self.sandbox().fs.download_file('/tmp/payouts-twin-results.tar.gz',
                                        str(self.path.parent / 'results.tar.gz'), timeout=180)
        self.state['results_exported_at'] = utc()
        self.save()

    def cleanup(self):
        if not self.state or self.state.get('cleanup_verified'):
            return
        identifier = self.state.get('sandbox_id') or self.state['sandbox_name']
        self.state['deletion_requested_at'] = utc()
        self.save()
        if exists_via_api(identifier):
            self.client.delete(self.sandbox(), timeout=60, wait=True)
        elif (not self.state.get('sandbox_id') and time.time() <
              self.state['started_epoch'] + self.state['ttl_minutes'] * 60 + 60):
            raise RuntimeError('Create response was uncertain and name lookup is currently absent; '
                               'creation may still complete. Retain state and recheck cleanup after TTL.')
        # A timeout/401/500 is never interpreted as successful cleanup.
        require(not exists_via_api(identifier), 'Sandbox still exists after delete')
        self.state['cleanup_verified'] = True
        self.state['deletion_time'] = utc()
        elapsed = (time.time() - self.state['started_epoch']) / 60
        resources = self.state.get('resources_allocated')
        self.state['approximate_usage'] = {'wall_minutes': round(elapsed, 3),
            'vcpu_minutes': round(elapsed * resources['cpu'], 3),
            'gib_memory_minutes': round(elapsed * resources['memory_gib'], 3),
            'gib_disk_minutes': round(elapsed * resources['disk_gib'], 3)} if resources else None
        self.save()


def run_managed(run, profile):
    original = None
    try:
        run.create()
        run.upload()
        run.test('smoke')
        if profile == 'full':
            run.test('full')
    except BaseException as exc:
        original = exc
    finally:
        # Additional interrupts must not abort export/deletion; server TTL covers kill/crash.
        for sig in (signal.SIGINT, signal.SIGTERM):
            signal.signal(sig, signal.SIG_IGN)
        if run.state:
            try:
                run.export()
            except Exception as exc:
                run.state['export_error_type'] = type(exc).__name__
                run.save()
                if original is None:
                    original = RuntimeError('Result export failed')
            try:
                run.cleanup()
            except Exception as exc:
                run.state['cleanup_error_type'] = type(exc).__name__
                run.save()
                raise RuntimeError('Cleanup unverified; retry cleanup.sh with the saved state; hard TTL remains active') from exc
    if original is not None:
        raise original


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('action', choices=['plan', 'run', 'create', 'upload', 'smoke', 'full', 'export', 'cleanup'])
    p.add_argument('--profile', choices=['smoke', 'full'], default='smoke')
    p.add_argument('--plan', default=str(ROOT / 'DAYTONA/execution-plan.json'))
    p.add_argument('--state', default=str(ROOT / 'DAYTONA/runs/current/state.json'))
    args = p.parse_args()
    if os.environ.get('DAYTONA_APPROVED') != '1' or args.action == 'plan':
        dry_run(args.action, args.plan)
        return
    # Cleanup deliberately does not depend on current acceptance, file hashes, or profile.
    if args.action == 'cleanup':
        require(Path(args.state).is_file(), 'No owned sandbox state exists; no deletion attempted')
        Run(args.state).cleanup()
        return
    plan = validate_plan(args.plan)
    require(args.action in ('run', 'export') or os.environ.get('DAYTONA_MANAGED_RUN') == '1',
            'Use run-and-cleanup.sh so all creation/test paths have finally cleanup')
    run = Run(args.state, plan)
    for sig in (signal.SIGINT, signal.SIGTERM):
        signal.signal(sig, lambda *_: (_ for _ in ()).throw(KeyboardInterrupt()))
    if args.action == 'run':
        run_managed(run, args.profile)
    elif args.action in ('smoke', 'full'):
        run.test(args.action)
    else:
        getattr(run, args.action)()


if __name__ == '__main__':
    try:
        main()
    except (RuntimeError, OSError, KeyError, ValueError) as exc:
        # Do not print SDK response bodies, request headers, or credentials.
        print('BLOCKED/FAILED: ' + str(exc), file=sys.stderr)
        sys.exit(1)
    except Exception as exc:
        print('BLOCKED/FAILED: ' + type(exc).__name__ + '; inspect saved run status without exposing SDK credentials', file=sys.stderr)
        sys.exit(1)
